services:
  db:
    image: postgres:18
    container_name: blablabook-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - blablabook-db-data:/var/lib/postgresql
    networks:
      - blablabook-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: blablabook-back
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npx tsx prisma/seed.ts && node dist/api/server.js"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blablabook-network
    

  front:
    build:
      context: ./front/next-demo 
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: blablabook-front
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - blablabook-network

volumes:
  blablabook-db-data:

networks:
  blablabook-network: