services:
  db:
    image: postgres:18
    container_name: blablabook-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - blablabook-db-data:/var/lib/postgresql/data
    networks:
      - blablabook-network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: blablabook-back
    command: sh -c "npx prisma db push && npm start"
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - blablabook-network

  front:
    build:
      context: ./front/next-demo 
      dockerfile: Dockerfile
    container_name: blablabook-front
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - blablabook-network

volumes:
  blablabook-db-data:

networks:
  blablabook-network: